FROM python:3.10-slim

WORKDIR /app

COPY server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY server/ .

CMD ["gunicorn", "-b", "0.0.0.0:5000", "main:app"]