# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY test_html_elements.py .

# Install Python dependencies from requirements.txt
# Ensure it includes selenium
RUN pip install Selenium pytest pytest-asyncio

# Install system dependencies required for Firefox and GeckoDriver
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    firefox-esr \
    && rm -rf /var/lib/apt/lists/*

# Install GeckoDriver
RUN GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4) \
    && wget -q "https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz" -O /tmp/geckodriver.tar.gz \
    && tar -xzf /tmp/geckodriver.tar.gz -C /usr/local/bin \
    && rm /tmp/geckodriver.tar.gz \
    && chmod +x /usr/local/bin/geckodriver

# Set display port to avoid crash
ENV DISPLAY=:99

# Command to run on container start
CMD ["pytest", "./test_html_elements.py"]