---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab5-1-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path:  /srv/nfs/hendris3
    server: 10.48.10.140
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab5-1-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: lab5-1-pvc
      containers:
        - name: app-container
          image: cithit/hendris3:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfs-storage
              mountPath: /nfs

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-1
spec:
  type: LoadBalancer
  loadBalancerIP: 10.48.10.214
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: my-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: my-service-1
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-2
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: my-app