---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab5-1-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path:  /srv/nfs/hendris3
    server: 10.48.10.140
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab5-1-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container-prod
          image: cithit/hendris3:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: nfs-storage
              mountPath: /nfs
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: lab5-1-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: api-service-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 10.48.10.214
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: api